# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: detect-private-key
      - id: check-ast

  - repo: local
    hooks:
      # Run the linter.
      - id: ruff
        name: ruff
        entry: ruff
        language: system
        types: [python]
        args: [ check, --fix ]
      # Run the formatter.
      - id: ruff-format
        name: ruff
        entry: ruff
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        language: system
        entry: pytest
        pass_filenames: false
        always_run: true
        stages: [ pre-push ]

  - repo: https://github.com/python-poetry/poetry
    rev: 1.5.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--no-update"]
        stages: [ pre-push ]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
